---
title: "R & R-Markdown"
subtitle: "Child & Adolescent Data Lab"
date: '`r format(Sys.Date(), format = "%B %d, %Y")`'
output: 
  ioslides_presentation:
    incremental: true
    widescreen: true
---

```{r, include = FALSE, echo = FALSE}
# mypresentation.html?presentme=true

# add notes in slides with:
# <div class="notes">
# Note
# Note
# Note
# </div>

# ---- AM's Notes ----
# Lacour study

# It can be useful to people who don't use R
# great for other languages, eg. python
# ```{r} versus ```{python}
# can be used with SAS!
# PSID data can be set up in a chunk, and then R can take care of the rest.
# Any variables made in a SAS chunk would have to be saved to disc :(
# But, code can read in the files if necessary

# have an abstract for monday before
# not an all-encompassing solution
# but...
# excellent for a dissertation & internal consistency

# reproducibility important for lots of work, but also for yourself
# keep track of things, with version control!
# don't save output!

# literate programming
# text and code all in one place, logical order
# data automatically updated to reflect external changes
# you test your code each time you knit/save the document
# 

# this comic is helpful http://www.phdcomics.com/comics/archive.php?comicid=1531

```

## Review & (brief) Outline

- Git/GitHub
- New questions?
- Collaborative tools to *centralize* your workflow.

- Extend on these concepts, as they relate to concepts in reproducibility
- Similar mindset as last-time: provide an overview, help demonstrate options that have
been highly useful in our work.

## What is Reproducibility?

"Reproducible research is the idea that data analyses, and more generally, scientific claims, are published with their data and software code so that others may verify the findings and build upon them." 
  -- [JHDS Reproducible Research Course](https://www.coursera.org/course/repdata)

 - Open Science

 - Good habits

## Who cares? | Essential tasks for researchers

- Good standards for scientific research
- But... Difficult to maintain if you work with sensitive data
- Perspective is valuable

- **3 major tasks:**

  1. Analysis
  2. Documentation/Description
  3. Generating a report/product to share with colleagues, or community

<div class="notes">
- Reproducibility is being able to fully recreate another individual's analysis on your local system.
- This makes it necessary to share both analytic code and data
- Infeasible for certain types of research
- DataLab can't share data-- too sensitive, major concerns with privacy for individuals involved
- But we benefit internally from good documentation and building in reproducibility between analysts
- Each individual working with the data should be able to step into an analysis file or processing file, and be able to contribute as necessary
</div>

## 


## Why R and R-Markdown?

- R is great for almost any type of data analysis you can think of
- If you've heard of it, there's probably a package for it
- Can be used to build things, in addition to just data-analysis

- Widely used, deep knowledge-base, open-source
- Great tools being developed with scientists in mind (like `ggplot2` & R-Markdown!)

## 
